storePassword=123456
keyPassword=123456
keyAlias=upload
storeFile=C:/Users/ITHUBBLR-SYSL-35/StudioProjects/Hfin_LMS_App/android/app/upload-keystore.jks

# C:\Users\ITHUBBLR-SYSL-35\StudioProjects\Hfin_LMS_App\android\app\upload-keystore.jks

# C:\Users\ITHUBBLR-SYSL-35\StudioProjects\Hfin_LMS_App\android\app\upload-keystore.jks